export const listTools = [
  {
    id: 1,
    nama: "Laravel",
    ket: "PHP Framework",
    gambar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-original.svg",
    dad: "100",
  },
  {
    id: 2,
    nama: "PHP",
    ket: "Backend Core",
    gambar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg",
    dad: "200",
  },
  {
    id: 3,
    nama: "Python",
    ket: "AI & Scripting",
    gambar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    dad: "300",
  },
  {
    id: 4,
    nama: "MySql",
    ket: "Database",
    gambar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
    dad: "400",
  },
  {
    id: 5,
    nama: "Vite",
    ket: "Build Tool",
    gambar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vitejs/vitejs-original.svg",
    dad: "500",
  },
  {
    id: 6,
    nama: "Git",
    ket: "Version Control",
    gambar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    dad: "600",
  },
];

export const listProyek = [
  {
    id: 1,
    title: "Mr. Mangkok POS",
    subtitle: "Point of Sales System",
    desc: "Comprehensive Point of Sales for Culinary Business.",
    fullDescription: "A complete Point of Sales system built with Laravel for managing culinary business operations. Features include inventory management, sales tracking, and reporting.",
    image: "https://placehold.co/600x400/000/FFF?text=POS+System",
    tech: ["Laravel", "SQL"],
    url: "https://github.com/aryakusuma",
    gradient: "linear-gradient(135deg, #1a1a1a 0%, #333333 100%)",
    borderColor: "#ffffff",
  },
  {
    id: 2,
    title: "GrowCash",
    subtitle: "Finance Management",
    desc: "Personal Finance & Budgeting App.",
    fullDescription: "A personal finance and budgeting application that helps users track expenses, set financial goals, and manage their money effectively.",
    image: "https://placehold.co/600x400/000/FFF?text=GrowCash",
    tech: ["PHP", "Finance"],
    url: "https://github.com/aryakusuma",
    gradient: "linear-gradient(135deg, #000000 0%, #1a1a1a 100%)",
    borderColor: "#ffffff",
  },
  {
    id: 3,
    title: "PKM Security",
    subtitle: "AI Security System",
    desc: "Face Recognition & Object Detection System.",
    fullDescription: "An advanced security system using Python and OpenCV for face recognition and object detection. Provides real-time monitoring and alerts.",
    image: "https://placehold.co/600x400/000/FFF?text=AI+Security",
    tech: ["Python", "OpenCV"],
    url: "https://github.com/aryakusuma",
    gradient: "linear-gradient(135deg, #333333 0%, #1a1a1a 100%)",
    borderColor: "#ffffff",
  },
  {
    id: 4,
    title: "OCR GenAI",
    subtitle: "AI-Powered OCR",
    desc: "Automated Journaling with Generative AI.",
    fullDescription: "An automated journaling system powered by Generative AI and OCR technology. Converts handwritten notes to digital text and generates insights.",
    image: "https://placehold.co/600x400/000/FFF?text=GenAI+OCR",
    tech: ["Python", "AI"],
    url: "https://github.com/aryakusuma",
    gradient: "linear-gradient(135deg, #1a1a1a 0%, #000000 100%)",
    borderColor: "#ffffff",
  },
];
